export default {
  "login": "Aayushjain-code",
  "id": 75216351,
  "node_id": "MDQ6VXNlcjc1MjE2MzUx",
  "avatar_url": "https://avatars.githubusercontent.com/u/75216351?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Aayushjain-code",
  "html_url": "https://github.com/Aayushjain-code",
  "followers_url": "https://api.github.com/users/Aayushjain-code/followers",
  "following_url": "https://api.github.com/users/Aayushjain-code/following{/other_user}",
  "gists_url": "https://api.github.com/users/Aayushjain-code/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Aayushjain-code/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Aayushjain-code/subscriptions",
  "organizations_url": "https://api.github.com/users/Aayushjain-code/orgs",
  "repos_url": "https://api.github.com/users/Aayushjain-code/repos",
  "events_url": "https://api.github.com/users/Aayushjain-code/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Aayushjain-code/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Aayush Jain",
  "company": null,
  "blog": "https://aayushjain.tech/",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "React.js | Frontend",
  "twitter_username": null,
  "public_repos": 29,
  "public_gists": 0,
  "followers": 18,
  "following": 7,
  "created_at": "2020-11-29T16:49:05Z",
  "updated_at": "2021-08-20T05:19:38Z"
};
